In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import mne
from mne.io import concatenate_raws, read_raw_edf
from mne.datasets import eegbci
from mne import Epochs, pick_types, find_events
import os

In [2]:
picks = [2,4,8,10,12,16,18] #index of 7 channels
event_id = dict(T1=2,T2=3)
tmin_mi, tmax_mi = 0, 2.99375
tmin_rest, tmax_rest = -1.5, 1.49375
path_root = "subjects/"
subjects = 109

In [3]:
def read_imagine_from_local(n):
    raw_files = []
    for i in range(1,n+1):
        sub_folder = path_root+"S"+str(i).zfill(3)+"/S"+str(i).zfill(3)+"R"
        sub_raw = []
        for j in range(4,15,4):
            full_path = sub_folder+str(j).zfill(2)+".edf"
            raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
    return raw_files

#write dataset and subjects of npz file for each subjects
def write_npz_file(x,y,folder,type,subject):
    if not os.path.exists(folder):
        os.makedirs(folder)
    filename = str(folder)+"/S"+str(subject).zfill(3)+type+".npz"
    np.savez(filename,x=x,y=y)

In [4]:
raw_files = read_imagine_from_local(subjects)

Extracting EDF parameters from subjects/S001/S001R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S001/S001R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S001/S001R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S002/S002R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S011/S011R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S011/S011R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S011/S011R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S0

Extracting EDF parameters from subjects/S020/S020R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S021/S021R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S021/S021R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S021/S021R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19839  =      0.000 ...   123.994 secs...
Extracting EDF parameters from subjects/S030/S030R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19839  =      0.000 ...   123.994 secs...
Extracting EDF parameters from subjects/S031/S031R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S031/S031R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S0

Extracting EDF parameters from subjects/S040/S040R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S040/S040R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S041/S041R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19839  =      0.000 ...   123.994 secs...
Extracting EDF parameters from subjects/S041/S041R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S050/S050R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S050/S050R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S051/S051R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19839  =      0.000 ...   123.994 secs...
Extracting EDF parameters from subjects/S0

Extracting EDF parameters from subjects/S060/S060R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S060/S060R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S060/S060R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S061/S061R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S070/S070R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S070/S070R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S070/S070R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S0

Extracting EDF parameters from subjects/S079/S079R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S080/S080R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S080/S080R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S080/S080R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...


<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully support

EDF+ with overlapping events are not fully supported
EDF+ with overlapping events are not fully supported
Extracting EDF parameters from subjects/S089/S089R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
EDF+ with overlapping events are not fully supported
EDF+ with overlapping events are not fully supported
Extracting EDF parameters from subjects/S089/S089R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
EDF+ with overlapping events are not fully supported
EDF+ with overlapping events are not fully supported
Extracting EDF parameters from subjects/S090/S090R04.edf...
EDF file detected
EDF annotations detected (consider using raw.f

<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully support

Extracting EDF parameters from subjects/S090/S090R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S090/S090R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S091/S091R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S091/S091R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully support

Extracting EDF parameters from subjects/S093/S093R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S093/S093R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S094/S094R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S094/S094R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully supported
  raw_files.append(read_raw_edf(full_path,preload=True,stim_channel="auto"))
<ipython-input-3-5bfbc93c4411>:8: RuntimeWarning: EDF+ with overlapping events are not fully support

Extracting EDF parameters from subjects/S101/S101R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S101/S101R12.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Extracting EDF parameters from subjects/S102/S102R04.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19679  =      0.000 ...   122.994 secs...
Extracting EDF parameters from subjects/S102/S102R08.edf...
EDF file detected
EDF annotations detected (consider using raw.find_edf_events() to extract them)
Setti

In [5]:
#from this, S88, 92, 100 have different sample rate
for i in range(len(raw_files)-1,-1,-1):
    if raw_files[i].info['sfreq'] != 160:
        print(i,raw_files[i].info['sfreq'])
        del raw_files[i]

#print length after delete
print("length of raw_files:",len(raw_files))

299 128.0
298 128.0
297 128.0
275 128.0
274 128.0
273 128.0
263 128.0
262 128.0
261 128.0
length of raw_files: 318


In [6]:
#fetch events from each raw_files
events = [find_events(r, shortest_event=0, stim_channel='STI 014') for r in raw_files]

Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel

29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
29 events found
Event IDs: [1 2 3]
Trigger channel has a non-zero initial value of 1 (consider using initial_event=True to detect this event)
Removing orphan

In [7]:
events[0]

array([[  672,     0,     3],
       [ 1328,     0,     1],
       [ 2000,     0,     2],
       [ 2656,     0,     1],
       [ 3328,     0,     2],
       [ 3984,     0,     1],
       [ 4656,     0,     3],
       [ 5312,     0,     1],
       [ 5984,     0,     3],
       [ 6640,     0,     1],
       [ 7312,     0,     2],
       [ 7968,     0,     1],
       [ 8640,     0,     3],
       [ 9296,     0,     1],
       [ 9968,     0,     2],
       [10624,     0,     1],
       [11296,     0,     3],
       [11952,     0,     1],
       [12624,     0,     2],
       [13280,     0,     1],
       [13952,     0,     2],
       [14608,     0,     1],
       [15280,     0,     3],
       [15936,     0,     1],
       [16608,     0,     2],
       [17264,     0,     1],
       [17936,     0,     3],
       [18592,     0,     1],
       [19264,     0,     2]], dtype=int64)

In [10]:
picks = pick_types(raw_files[0].info, meg=False, eeg=True, stim=False, eog=False,exclude='bads')

In [11]:
events23 = []
labels = []
for e1 in events:
    tmp = []
    tmp2 = []
    for e2 in e1:
        if e2[-1] == 2:
            tmp.append(e2)
            tmp2.append('left')
        elif e2[-1] == 3:
            tmp2.append('right')
            tmp.append(e2)
    events23.append(np.array(tmp))
    labels.append(np.array(tmp2))
labels = np.array(labels)

In [12]:
print(events23[0])
print(labels[0])

[[  672     0     3]
 [ 2000     0     2]
 [ 3328     0     2]
 [ 4656     0     3]
 [ 5984     0     3]
 [ 7312     0     2]
 [ 8640     0     3]
 [ 9968     0     2]
 [11296     0     3]
 [12624     0     2]
 [13952     0     2]
 [15280     0     3]
 [16608     0     2]
 [17936     0     3]
 [19264     0     2]]
['right' 'left' 'left' 'right' 'right' 'left' 'right' 'left' 'right'
 'left' 'left' 'right' 'left' 'right' 'left']


In [13]:
x_mi = [Epochs(r, events23[i],event_id,tmin=tmin_mi,tmax=tmax_mi,proj=True,picks=picks,baseline=None,preload=True).get_data().transpose((0,2,1)) for i,r in enumerate(raw_files)]

15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setti

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

In [14]:
x_rest = [Epochs(r, events23[i],event_id,tmin=tmin_rest,tmax=tmax_rest,proj=True,picks=picks,baseline=None,preload=True).get_data().transpose((0,2,1)) for i,r in enumerate(raw_files)]

15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setti

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
Loading data for 15 events and 480 original time points ...
0 bad epochs dropped
15 matching events found
No baseline correct

In [15]:
cnt = 0
for i in range(subjects):
    if i == 87 or i == 91 or i == 99:
        continue
    for j in range(3): 
        write_npz_file(x_mi[cnt],labels[cnt],"down_eeg","_mi",i+1)
        write_npz_file(x_rest[cnt],labels[cnt],"down_eeg","_rest",i+1)
        print(cnt)
        cnt += 1
    print(i," is writed.")

0
1
2
0  is writed.
3
4
5
1  is writed.
6
7
8
2  is writed.
9
10
11
3  is writed.
12
13
14
4  is writed.
15
16
17
5  is writed.
18
19
20
6  is writed.
21
22
23
7  is writed.
24
25
26
8  is writed.
27
28
29
9  is writed.
30
31
32
10  is writed.
33
34
35
11  is writed.
36
37
38
12  is writed.
39
40
41
13  is writed.
42
43
44
14  is writed.
45
46
47
15  is writed.
48
49
50
16  is writed.
51
52
53
17  is writed.
54
55
56
18  is writed.
57
58
59
19  is writed.
60
61
62
20  is writed.
63
64
65
21  is writed.
66
67
68
22  is writed.
69
70
71
23  is writed.
72
73
74
24  is writed.
75
76
77
25  is writed.
78
79
80
26  is writed.
81
82
83
27  is writed.
84
85
86
28  is writed.
87
88
89
29  is writed.
90
91
92
30  is writed.
93
94
95
31  is writed.
96
97
98
32  is writed.
99
100
101
33  is writed.
102
103
104
34  is writed.
105
106
107
35  is writed.
108
109
110
36  is writed.
111
112
113
37  is writed.
114
115
116
38  is writed.
117
118
119
39  is writed.
120
121
122
40  is writed.
123
124
125
4