In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import mne
from mne.datasets import eegbci
from mne import Epochs, pick_types, find_events
import os
import scipy.io as sio

In [113]:
def read_dataset(dataset,num):
    path = "dataset"+str(dataset)+"/"
    if dataset == 1:
        path += "A"
    elif dataset == 2:
        path += "S"
    elif dataset == 4:
        path += "B"
    e = []
    t = []
    for i in range(1,num+1):
        e.append(sio.loadmat(path+str(i).zfill(2)+"E.mat"))
        t.append(sio.loadmat(path+str(i).zfill(2)+"T.mat"))
    return t, e

In [114]:
e, t = read_dataset(4,9)

In [332]:
def prep_e(data):
    data1 = list(data['data'].tolist()[0][0][0][0])
    data2 = list(data['data'].tolist()[0][1][0][0])
    return (data1, data2)

def prep_t(data):
    data1 = list(data['data'].tolist()[0][0][0][0])
    data2 = list(data['data'].tolist()[0][1][0][0])
    #data3 = list(data['data'].tolist()[0][2][0][0])
    return (data1, data2)

In [334]:
def features(data):
    x = data[0][:,:22]
    trial_raw = data[1].tolist()
    trial = [num for e in trial_raw for num in e]
    y = [num for e in data[2] for num in e]
    atf = [num for e in data[5] for num in e]
    rate = data[3][0].tolist()
    
    return x,trial,y,atf,rate

In [335]:
data = [prep_t(tt) for tt in t]    

In [336]:
data[0][0][0].shape

(466314, 6)

In [149]:
x,trial,y,atf,rate = features(t1[7])

In [150]:
x.shape

(787729, 3)

In [190]:
len(trial)

160

In [152]:
atf

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [153]:
rate

[250]

In [154]:
y

[0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0]

In [224]:
dataset = []
for ee in e1:
    dataset.append(features(ee))
for ee in e2:
    dataset.append(features(ee))

In [189]:
#0 = data, 1 = trial, 2 = label, 3 = sample rate, 4 = ?, 5 = artifact, 6 = gender, 7 = age
for i in range(len(e[0]['data'][0][0][0][0])):
    print(len(e[0]['data'][0][0][0][0][i]),'*'*99)
    print(e[0]['data'][0][0][0][0][i])

466314 ***************************************************************************************************
[[ -3.05250305  -3.02808303  -1.12332112 -47.37484737  -4.3956044
   46.3980464 ]
 [ -2.97924298  -0.63492063  -1.07448107 -47.37484737 -13.18681319
   34.18803419]
 [ -2.95482295  -0.21978022  -0.58608059 -39.56043956  -8.3028083
   33.6996337 ]
 ...
 [  3.05250305   3.63858364   5.00610501  11.23321123  -7.32600733
   12.21001221]
 [  1.97802198   3.73626374   4.61538462  10.25641026 -12.21001221
    5.37240537]
 [  1.53846154   2.22222222   3.61416361  -1.46520147 -26.37362637
    2.44200244]]
160 ***************************************************************************************************
[[ 54350]
 [ 57071]
 [ 59328]
 [ 61597]
 [ 63849]
 [ 66121]
 [ 68564]
 [ 70881]
 [ 73283]
 [ 75597]
 [ 78222]
 [ 80543]
 [ 83165]
 [ 85764]
 [ 88065]
 [ 90428]
 [ 93019]
 [ 95480]
 [ 97948]
 [100253]
 [102869]
 [105511]
 [108036]
 [110745]
 [113256]
 [115537]
 [117839]
 [120555]
 [12296

In [225]:
for d in dataset:
    print(len(d[0]))
    print(len(d[1]))
    print(len(d[2]))
    print(len(d[3]))
    print(d[4])
    print('*'*99)

466314
160
160
160
[250]
***************************************************************************************************
361830
120
120
120
[250]
***************************************************************************************************
464675
160
160
160
[250]
***************************************************************************************************
467479
160
160
160
[250]
***************************************************************************************************
417020
160
160
160
[250]
***************************************************************************************************
469991
160
160
160
[250]
***************************************************************************************************
470344
160
160
160
[250]
***************************************************************************************************
474835
160
160
160
[250]
***************************************************************************************************


In [226]:
d[1]

[54350,
 56816,
 59529,
 62272,
 64693,
 67131,
 69825,
 72379,
 74849,
 77397,
 79763,
 82114,
 84384,
 86975,
 89226,
 91517,
 94059,
 96370,
 98912,
 101450,
 104026,
 106699,
 109227,
 111668,
 113940,
 116443,
 119086,
 121386,
 123684,
 126067,
 128364,
 130832,
 133227,
 135612,
 138042,
 140296,
 142951,
 145472,
 147918,
 150297,
 155930,
 158396,
 161109,
 163852,
 166273,
 168711,
 171405,
 173959,
 176429,
 178977,
 181343,
 183694,
 185964,
 188555,
 190806,
 193097,
 195639,
 197950,
 200492,
 203030,
 205606,
 208279,
 210807,
 213248,
 215520,
 218023,
 220666,
 222966,
 225264,
 227647,
 229944,
 232412,
 234807,
 237192,
 239622,
 241876,
 244531,
 247052,
 249498,
 251877,
 257510,
 259976,
 262689,
 265432,
 267853,
 270291,
 272985,
 275539,
 278009,
 280557,
 282923,
 285274,
 287544,
 290135,
 292386,
 294677,
 297219,
 299530,
 302072,
 304610,
 307186,
 309859,
 312387,
 314828,
 317100,
 319603,
 322246,
 324546,
 326844,
 329227,
 331524,
 333992,
 336387,
 3

In [227]:
d[2]

[1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1]

In [228]:
d[3]

[0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0]

In [229]:
z = list(zip(d[3],d[2],d[1]))

In [230]:
z

[(0, 1, 54350),
 (1, 2, 56816),
 (0, 1, 59529),
 (0, 2, 62272),
 (0, 2, 64693),
 (0, 2, 67131),
 (1, 1, 69825),
 (0, 2, 72379),
 (1, 1, 74849),
 (0, 1, 77397),
 (0, 1, 79763),
 (0, 2, 82114),
 (0, 1, 84384),
 (0, 1, 86975),
 (1, 2, 89226),
 (0, 2, 91517),
 (0, 2, 94059),
 (0, 1, 96370),
 (0, 2, 98912),
 (0, 2, 101450),
 (0, 2, 104026),
 (0, 1, 106699),
 (1, 1, 109227),
 (0, 1, 111668),
 (0, 2, 113940),
 (0, 1, 116443),
 (0, 2, 119086),
 (0, 1, 121386),
 (0, 2, 123684),
 (1, 1, 126067),
 (0, 1, 128364),
 (1, 2, 130832),
 (0, 2, 133227),
 (1, 1, 135612),
 (0, 2, 138042),
 (0, 2, 140296),
 (0, 1, 142951),
 (1, 1, 145472),
 (0, 2, 147918),
 (0, 1, 150297),
 (0, 2, 155930),
 (0, 2, 158396),
 (0, 1, 161109),
 (0, 1, 163852),
 (0, 1, 166273),
 (1, 2, 168711),
 (0, 1, 171405),
 (0, 1, 173959),
 (0, 2, 176429),
 (0, 1, 178977),
 (0, 1, 181343),
 (0, 1, 183694),
 (0, 2, 185964),
 (0, 2, 188555),
 (1, 1, 190806),
 (0, 1, 193097),
 (0, 1, 195639),
 (0, 2, 197950),
 (0, 1, 200492),
 (0, 2, 203030),

In [233]:
no_art = [(b,c) for a,b,c in z if a == 0]

In [234]:
no_art

[(1, 54350),
 (1, 59529),
 (2, 62272),
 (2, 64693),
 (2, 67131),
 (2, 72379),
 (1, 77397),
 (1, 79763),
 (2, 82114),
 (1, 84384),
 (1, 86975),
 (2, 91517),
 (2, 94059),
 (1, 96370),
 (2, 98912),
 (2, 101450),
 (2, 104026),
 (1, 106699),
 (1, 111668),
 (2, 113940),
 (1, 116443),
 (2, 119086),
 (1, 121386),
 (2, 123684),
 (1, 128364),
 (2, 133227),
 (2, 138042),
 (2, 140296),
 (1, 142951),
 (2, 147918),
 (1, 150297),
 (2, 155930),
 (2, 158396),
 (1, 161109),
 (1, 163852),
 (1, 166273),
 (1, 171405),
 (1, 173959),
 (2, 176429),
 (1, 178977),
 (1, 181343),
 (1, 183694),
 (2, 185964),
 (2, 188555),
 (1, 193097),
 (1, 195639),
 (2, 197950),
 (1, 200492),
 (2, 203030),
 (2, 205606),
 (1, 208279),
 (2, 210807),
 (1, 213248),
 (2, 218023),
 (2, 220666),
 (1, 225264),
 (1, 229944),
 (1, 232412),
 (2, 234807),
 (2, 237192),
 (1, 239622),
 (1, 241876),
 (2, 244531),
 (2, 247052),
 (2, 249498),
 (1, 251877),
 (1, 257510),
 (1, 259976),
 (1, 265432),
 (2, 267853),
 (1, 270291),
 (1, 272985),
 (2, 27

In [235]:
label, trial = zip(*no_art)

In [240]:
def split_data(data):
    x, trial, y, atf, rate = features(data)
    group1 = list()
    group2 = list()
    group3 = list()
    group4 = list()
    a = list(range(0, X.shape[0])) 
    
    z = list(zip(atf, y, trial))
    filtered = [(b,c) for a,b,c in z if a == 0]
    label, trial_filter = zip(*filtered)

    for i in a:
        if i in trial_filter:
            group1.append(X[i:i+2*sec])
            group2.append(X[i+int(2.5*sec):i+int(4.5*sec)])
            group3.append(X[i+4*sec:i+6*sec])
            group4.append(X[i+int(6.5*sec):i+int(8.5*sec)])
            
    arr1 = np.array(group1)
    arr2 = np.array(group2)
    arr3 = np.array(group3)
    arr4 = np.array(group4)
    label = np.array(label)
    
    return arr1, arr2, arr3, arr4, label

In [340]:
t1, e1 = read_dataset(1,9)
t4, e4 = read_dataset(4,9)

In [345]:
data_t1 = [prep_t(tt) for tt in t1]
data_e1 = [prep_e(ee) for ee in e1]
data_t4 = [prep_t(tt) for tt in t4]
data_e4 = [prep_e(ee) for ee in e4]

In [367]:
for i in range(len(data_t4)):
    for j in range(len(data_t4[i])):
        print('-'*50,i+1,j)
        print(data_t4[i][j][2])

-------------------------------------------------- 1 0
[[2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]]
-------------------------------------------------- 1 1
[[2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [2]
 [2]